### ISSUE TITLE
Add sentinel support

### ISSUE THREAD

**Issue by ghost** [gomodule/redigo#11]
http://redis.io/topics/sentinel-clients

I have a rough plan in mind on how to implement sentinel support, but I have not done it yet because I don't need it.

**Comment by hbcheng** [comment]
Hi, this feature is something that would improve our deployment and I'm willing to help out on this. Seeing as there hasn't been any noise on this in some time, I was wondering if:

a) There is any existing work on this that you or any of the contributors are aware of, and 

b) If your thoughts on design or implementation have changed in the ~year and a half since this was last discussed.

**Comment by garyburd** [comment]
For those following along on the issue tracker, @hbcheng is now taking a look at this feature.

**Comment by hbcheng** [comment]
Pull request is submitted, pr #120.
