### ISSUE TITLE
Inconsistency with documented redis behavior

### ISSUE THREAD

**Issue by darethas** [gomodule/redigo#341]
Hello, I noticed with the SPOP command, redis documentation states nil should be returned when the key does not exist, however `Do("SPOP", nonexistantkey, 1)` returns an empty slice of `[]interface{}` values. Is there a piece of the puzzle I am missing here?

I am using the latest version of redigo on go 1.10.  Thank you.

**Comment by nilslice** [comment]
@darethas - a boolean comparison between `nil` (the value in Go) and any empty slice will be true. 

for example, checking the returned value from the call to `vals, err := Do(...) []interface{}` 
```go
if vals == nil {
    // vals (an empty []interface{}) is nil, meaning no values were found at your nonexistantkey
}
```

does that answer your question? apologies if I am missing some context.

**Comment by darethas** [comment]
@nilslice Thanks for the reply -- no apologies needed, but yeah I knew that, but I also know it is just as valid to return nil for an interface{} return parameter in a function, so it seems like r.Do() could do what redis documents and return nil instead of an empty slice which has a different meaning (that the key was found, but nothing was in it)

**Comment by nilslice** [comment]
Ok, I understand now what you mean. As per the source,`nil` _is_ returned when redigo can easily understand no reply should be returned (i.e. in the case of a failure, or no command sent). See: https://github.com/gomodule/redigo/blob/master/redis/conn.go#L619

However, in order to determine that there are no values found is something that would require redigo to optimistically scan the values into your type. The `interface{}` type returned implies that the caller (you) should scan the reply into some type you're expecting and check the length if it is a slice. I could be missing a step there though re: the thinking behind this (I'm not an author of redigo)

**Comment by redmondnoodle** [comment]
The response from the server is an [empty array](https://github.com/gomodule/redigo/blob/9352ab68be133885e31a43661cc42a220cb8e821/redis/conn.go#L548-L555), not [null](https://github.com/gomodule/redigo/blob/9352ab68be133885e31a43661cc42a220cb8e821/redis/conn.go#L546).

**Comment by garyburd** [comment]
The Redis server returns a zero length array and that's what Redigo returns to the application.

Redigo does not translate return values on a per-command basis to match the documentation.
