### ISSUE TITLE
Support Go Modules

### ISSUE THREAD

**Issue by garyburd** [gomodule/redigo#366]
This repo was moved from here from garyburd/redigo. At the time of the move, I made some minor breaking changes to the API and tagged a v2.0.0 release.

The v2.0.0 release turned out to be a problem when Go Modules were introduced. It's now clear that I should have deleted previous v1.x.x releases from the repo and tagged a new v1.0.0 release.

I was my intent that this repo have one major semantic version until the next breaking API change is made. Let's call the major semantic version as of today as version N. 

~~It's possible that users who employ a dependency management tool are using the tags copied over from garyburd/redigo. These users are on major version N-1.~~  Edit: These versions do not compile because they have a package import comment for garyburd/redigo.  It's safe to assume that there are no users of these versions.

Users of Go 1.5+  who do not employ a dependency management tool should continue to get the latest of major version N.  This works today and should continue to be supported until Go Modules is widely adopted.

Users who opt into Go Modules should not need to change their code.

Because I expect Go Modules to be widely adopted before major version N+1 of this package is created, it's acceptable to require a dependency management tool to get version N+1.

Adding a go.mod file to a v2.x.x release changes the path of the package to github.com/gomodule/redigo/v2.  This requires a change to all importers of the packages and does not work for users on Go 1.8 and earlier.

See previous discussion in #365 and #363.

**Comment by ostcar** [comment]
I am not sure if I do something wrong or if the current state is broken.

I try to use the new go modules on an existing project. When I call `go build` go installs all dependencies including redigo but fails with

```
../../.gopath/pkg/mod/github.com/garyburd/redigo@v2.0.0+incompatible/redis/pool.go:28:2: use of internal package github.com/gomodule/redigo/internal not allowed
```

Do you know how to solve this or do you have a workaround?

**Comment by elithrar** [comment]
The error refers to garyburd/redigo and not gomodule/redigo (the correct
path). How are you importing the library in your packages?

**Comment by ostcar** [comment]
sry. I found the reason. My question was off topic here so I deleted it.

**Comment by huaguoping** [comment]
Hi, i can not build. get the error:

> /workpath/go/pkg/mod/github.com/garyburd/redigo@v2.0.0+incompatible/redis/pool.go:28:2: use of internal package github.com/gomodule/redigo/internal not allowed

And i got 2 redigo in my go.mod...
> require (
	...
	github.com/garyburd/redigo v2.0.0+incompatible
	github.com/gomodule/redigo v2.0.0+incompatible // indirect
        ...
)

go version: v1.11

**Comment by garyburd** [comment]
@huaguoping Use github.com/garyburd/redigo v1.6.0 instead of v2.0.0.

**Comment by huaguoping** [comment]
> @huaguoping Use github.com/garyburd/redigo v1.6.0 instead of v2.0.0.

Thx. 👍

**Comment by jrefior** [comment]
Per "semantic import versioning", introduced with go modules in go 1.11, incrementing the major version of a module above 1 requires a new import path.  See:

> In semantic versioning, changing the major version number indicates a lack of backwards compatibility with earlier versions. To preserve import compatibility, the go command requires that modules with major version v2 or later use a module path with that major version as the final element. For example, version v2.0.0 of example.com/m must instead use module path example.com/m/v2, and packages in that module would use that path as their import path prefix, as in example.com/m/v2/sub/pkg. Including the major version number in the module path and import paths in this way is called "semantic import versioning".

[Module compatibility and semantic versioning](https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning)

The preferred way to do this is usually to create a `v2` branch, append `/v2` to the module name (first line of the go.mod file), update import paths to include the `/v2`, and tag a new `v2.x.x` release.  That should be all that's required.  Imports that leave off the v2 will get the highest v1.x.x availlable, while imports that include the v2 will get the highest v2.x.x available.

See [From Repository to Modules](https://research.swtch.com/vgo-module).

**Comment by elithrar** [comment]
The challenge is that the repository is already v2, because it was tagged
as such well before Modules existed (and they are still not “final”).

You could publish a v2.0.1 and update the import path, but at risk of
breaking existing users & module users alike.

**Comment by jrefior** [comment]
> Existing users do not need to change code or tools to continue using the current version of the package. This includes users on Go 1.8 and earlier, users who fetch the code with go get, etc.

Glide allows Go 1.5+ users to lock packages at specific versions.  But if I understand this requirement correctly, you are also trying to support users of Go 1.8 and earlier who do not employ a dependency management tool, and will always just get "latest" with `go get` -- is that correct?

Does the current "latest" work for them, or are you trying to move them back to some previous version via the next release?

**Comment by garyburd** [comment]
The current latest works Go 1.5 and up.

**Comment by garyburd** [comment]
@jrefior: I updated the issue to clarify where we are today and what I see as the requirements. Let me know if that does not answer your questions.

All: I deleted comments regarding an unrelated issue. 

The discussion at [gofrs/uuid #61](https://github.com/gofrs/uuid/issues/61) may be relevant here.

Does it work to orphan v2.0.0 and continue continue releases on v1.x.x where a go.mod file can be added seamlessly?

**Comment by elithrar** [comment]
What happens to users who pulled v2.0.0 already, and have it in their
dependency manifest?

**Comment by jrefior** [comment]
Right, that's the question, because that's where there's possible downside.  And the reason for doing some testing with different dependency management tools.

So for example, if I'm on go 1.11.4, and I "restore" v2.0.0 by deleting the go.mod file and committing and tagging, then import jrefior/redigo from some other project via go get, I'll see this:
```
$ go get github.com/jrefior/redigo/redis
go: finding github.com/jrefior/redigo/redis latest
go: finding github.com/jrefior/redigo v2.0.0+incompatible
go: downloading github.com/jrefior/redigo v2.0.0+incompatible
$ cat go.mod
module opensource/test01

require github.com/jrefior/redigo v2.0.0+incompatible // indirect
$ cat go.sum
github.com/jrefior/redigo v2.0.0+incompatible h1:DnvDEZJV+Z/ulWZhD5r/L7/bziq203lzvd2AUi5C9S8=
github.com/jrefior/redigo v2.0.0+incompatible/go.mod h1:msepy20fPwm2qIMjp3xi0iLG66J+DoYk66NT0Jt7Oso=
```
Now when I delete tag v2.0.0, and commit the go.mod file again and tag v1.8.0, now I try to build my test project again:
```
$ go build
$
```
The build just works.  But that's because it's loading it from my module cache (`$GOPATH/pkg/mod`).  If I set a new module cache by changing my gopath, trying to build errors:
```
$ go build
go: finding github.com/jrefior/redigo v2.0.0+incompatible
go: github.com/jrefior/redigo@v2.0.0+incompatible: unknown revision v2.0.0
go: error loading module requirements
```
And the binary is not built.  So then the user has to take some action to resolve the problem.  In this situation a `go get` or `go get -u` won't resolve it, even if you specify the new version you want.  Your only solution is to manually edit the go.mod file (either change the version or delete the requirement and let the go tool find it again on build).

In my view, that's not a great user experience.  This test could be repeated with glide and other dependency management tools.

Unfortunately I think trying to continue with development/maintenance on v1.x.x only without deleting v2.0.0 is probably worse, as many users trying to get latest will inadvertently wind up with v2.0.0, failing silently to get the latest code.

To avoid both of those you can set the module name to `github.com/gomodule/redigo/v2` and require go-module-aware users to add the `v2` to their import path to get v2.x.x code, if you're willing to do that.

**Comment by garyburd** [comment]
How about this:

- Add go.mod file with content:

       module github.com/gomodule/redigo/v2

- Change tests to import  github.com/gomodule/redigo/v2
- Tag a new v2.x.x. release
- Create a v1 branch and change go.mod on the branch to:

       module github.com/gomodule/redigo

- Tag v1.x.x release on v1 branch.
- Write script to:
   - Tag v2.x.x release
   - Merge changes from master to v1 branch
   - Tag v1.x.x release on the v1 branch

Tests will fail in the v1 branch.  Everything else should work.

**Comment by arnottcr** [comment]
Since it appears you intend for most consumers to use the `v1.7.0` tag, not the old `v2.0.0` tag, what if you release `v1.7.1` with `module github.com/gomodule/redigo` and on a separate, say `v2` branch, release `v2.0.1` with `module github.com/gomodule/redigo/v2`.

I would imagine that the `v2.0.0` codebase is not being supported, so this proposal serves to have module customers ignore the `v2` line unless they ask for it specifically. The only downside is that it locks you into `v2` api compatibility, but I think the `v2.0.0` tag already does that.

If this is a viable solution, I think #413 can serve for the `v1.7.1` change, would you like me to spin up another change for `v2.0.1`?

**Comment by garyburd** [comment]
@arnottcr Because it was a mistake to create the v2 tag, I'd like to ignore it.  The problem is that people will assume that v2 is better than v1.  The status of v2 can be explained in the README, but that will only help those who actually read the file.

Perhaps the best option is to maintain v1 and v2 in parallel with v1 as the main line of development,  A script can be written to merge changes from v1 to v2 and create the v2 tags as needed. This is the opposite of what I described [here](https://github.com/gomodule/redigo/issues/366#issuecomment-455831640).

**Comment by arnottcr** [comment]
that makes sense, I think in that case you may want to consider the [major subdirectory option]() and use type aliases in conjunction with a tool like [goforward]() to make things easier on yourself. The only breakage you would see, is for people using tools like `dep`, `glide`, etc. who are currently consuming the `v2.x.x` line from the import `github.com/gomodule/redigo`. If you are fine with this, I can mock up a PR, otherwise I would suggest jumping to `v3`, for "active development".

**Comment by danqing** [comment]
Agreed that maybe we can just get a v3. Now every time I do things like `go get -u` my 1.7 will be bumped to 2.0 and I have to manually edit the files to lower the version, which is not ideal..

**Comment by dcormier** [comment]
Is there any reason to just not delete the `v2.0.0` tag?

**Comment by stevenh** [comment]
It's not 100% ideal but a v3 may be the lesser of all evils, thoughts?

**Comment by arnottcr** [comment]
Tags *MUST* not be deleted per the semver spec, it also cannot be deleted from the module proxy, so the delete will be a noop.

**Comment by dcormier** [comment]
> It's not 100% ideal but a v3 may be the lesser of all evils, thoughts?

Sounds good to me. Better than the current situation.

**Comment by rkuska** [comment]
(Just fyi) To use the latest version of this module you can fallback to pseudoversioning:

`go get github.com/gomodule/redigo@v0.0.0-20191011215927-4f569a470858`

and then just replace your original gomodule/redigo in `go.mod` with `github.com/gomodule/redigo v0.0.0-20191011215927-4f569a470858`

**Comment by jrefior** [comment]
Noticed this post from rsc in another thread on adding Go Modules support to an open source package, and thought some people considering options in this issue might find it helpful:
[Russ Cox reply to Badger v2 post](https://discuss.dgraph.io/t/important-badger-v2-0-0-will-require-go-modules/5306/3)

**Comment by Jim-Lambert-Bose** [comment]
You could just create a long lived v2 branch with a go.mod with the proper v2 module name, and then merge all released changes into that branch from master every time you cut a new v1 release... then use the v2 branch to make releases for v2...keeping them in sync with the v1 releases.  This would allow `go get` installs that don't specify the v2 module name to work as expected and the v2 versions will also stay in sync.
