### ISSUE TITLE
cause redigo 'protocolError("long response line")' when the response is too long from redis

### ISSUE THREAD

**Issue by Mark3K** [gomodule/redigo#380]
The method `readLine` of `conn` calls `bufio.ReadSlice` with `\n`, if the response from redis is too long(>4096, the `bufio.defaultBufSize` is `4096`), will cause `protocolError`.

can `redigo` provide a way to customize the receive buffer size or use the `bufio.ReadBytes` instead?

**Comment by itamarhaber** [comment]
Hello @Mark3K 

Could you please provide a reproduction of the issue?

**Comment by garyburd** [comment]
@Mark3K If you encountered this error in practice, then it's likely that your application called Receive concurrently.  Run your application with the [race detector](https://golang.org/doc/articles/race_detector.html) to debug the issue.

Otherwise, I second itamarhaber's request.  Please provide a reproduction of the issue.

**Comment by itamarhaber** [comment]
@garyburd ty for enlightening me wrt race detector - I wish I had more time to spend being a Gopher :)

**Comment by daiguadaidai** [comment]
My code is

```
_, err = redisInstance.Conn.Do("monitor")
if err != nil {
	return err
}

for {
	data, err := ri.Conn.Receive()
	if err != nil {
		return err
	}
}
```
when `monitor` data more than `4096B`, occur this error

Temporary approach:
edit `conn.go` file `readLine()` function as follows：

`p, err := c.br.ReadSlice('\n')` replace `p, err := c.br.ReadBytes('\n')`

```
func (c *conn) readLine() ([]byte, error) {
	p, err := c.br.ReadBytes('\n')
	if err == bufio.ErrBufferFull {
		return nil, protocolError("long response line")
	}
	if err != nil {
		return nil, err
	}
	i := len(p) - 2
	if i < 0 || p[i] != '\r' {
		return nil, protocolError("bad response line terminator")
	}
	return p[:i], nil
}
```

**Comment by daiguadaidai** [comment]
read buffer size can be turned into a dynamic parameter so that the user can specify.
and edit `conn.go` file `Dial` function

code
```
	c := &conn{
		conn:         netConn,
		bw:           bufio.NewWriter(netConn),
		br:           bufio.NewReader(netConn),
		readTimeout:  do.readTimeout,
		writeTimeout: do.writeTimeout,
	}
```
change to
```
	c := &conn{
		conn:         netConn,
		bw:           bufio.NewWriter(netConn),
		br:           bufio.NewReaderSize(netConn),
		readTimeout:  do.readTimeout,
		writeTimeout: do.writeTimeout,
	}
```

**Comment by garyburd** [comment]
The [MONITOR command](https://redis.io/commands/monitor) is not supported by this client because the command does not follow the [RESP protocol](https://redis.io/topics/protocol). More specifically, the server begins sending a stream of commands to the client after receiving the command.  The server does not send a response.

To use the MONITOR command, dial a TCP connection to the server, write the bytes `*1\r\n$7\r\nMONITOR\r\n` to the connection and begin reading the connection.

	c, err := net.Dial("tcp", "127.0.0.1:6379")
	if err != nil {
		log.Fatal(err)
	}
	if _, err := io.WriteString(c, "*1\r\n$7\r\nMONITOR\r\n"); err != nil {
		log.Fatal(err)
	}
	log.Fatal(io.Copy(os.Stdout, c))

**Comment by garyburd** [comment]
I take that back.  Although there's no response, the server writes a sequence of RESP strings. 

I'll need to think about what the best approach is.  I don't want to add a dial option because it makes the API more complex for what is a corner case.

**Comment by elithrar** [comment]
Possibly a “Monitor” method that returns an iterator - e.g. resp.Next() - ?

**Comment by garyburd** [comment]
I had no idea that MONITOR writes a sequence RESP  simple strings.  Simple strings returned from "regular" commands are all short (OK, PONG, ...).

Thank you for reporting the issue.
