### ISSUE TITLE
Create method ReceiveAny() for Conn?

### ISSUE THREAD

**Issue by jiuker** [gomodule/redigo#455]
I need Send PSYNC ? -1 cmd to redis
But I get A error:
redigo: bad bulk string format (possible server error or unsupported concurrent read by application)
I read the code,the code parse unknown type;so it is error?
So can you  create a method ReceiveAny() to return all byte?I find A tool to parse It.
the parse rbd tool is redis-port,if you want to do this.

**Comment by stephenandwood** [comment]
Dial a TCP connection, write "*1\r\n$5\r\nPSYNC\r\n" to the connection and read the PSYNC response.

**Comment by jiuker** [comment]
I I know this way, but the introduction says that all commands are supported, so I think it is necessary to support, or put forward unsupported commands in the introduction

**Comment by stephenandwood** [comment]
The introduction should be updated to say "A Print-like API with support for all Redis commands with standard return values.".

**Comment by stevenh** [comment]
`PSYNC` is [documented as having a non standard return value](https://redis.io/commands/psync) so it's not surprising this doesn't work as its not really a request a client is meant to send.

If this could implemented in a clean way then happy to accept a PR to fix this, otherwise I think the best we can do is document this exception.
