### ISSUE TITLE
Error when use lua

### ISSUE THREAD

**Issue by aleczhangj** [gomodule/redigo#533]
There may be something wrong with [this line](https://github.com/gomodule/redigo/blob/0b0ad3d61a939c7a5dc5ed56fa10668d4032304c/redis/script.go#L69
)

In my case, the redis server support command "EVAL" but not "EVALSHA"，when use "EVALSHA" to exec the lua script, it returns "ERR Proxy fail to parse command", which not match the condition in  [this line](https://github.com/gomodule/redigo/blob/0b0ad3d61a939c7a5dc5ed56fa10668d4032304c/redis/script.go#L69
), so it will never use "EVAL" to exec the script

Temporarily, i use SEND, FLUSH, RECEIEVE  command to fix this issue which is not elegant. 
And, I really want to know, is there a more elegant way. thanks

**Comment by stevenh** [comment]
Do you have an example?

**Comment by chenjie199234** [comment]
@aleczhangj @stevenh 
that's because you are not communicate with the redis server.
you are communicate with the proxy.
if you communicate with the redis server,when the script not installed, "NOSCRIPT" error will return.
this is not the problem of the redis driver.
redis driver shouldn't compatible the proxy.
this is the proxy's problem.

**Comment by stevenh** [comment]
Agreed with @chenjie199234 seems like a proxy bug not a driver bug.
