### ISSUE TITLE
Add PubSubConn.ReceiveContext()

### ISSUE THREAD

**Issue by RelicOfTesla** [gomodule/redigo#592]
1. add "PubSubConn.ReceiveContext" support watch the <-context.Done() .
 because "redis.ReceiveContext" is return native redis response. was not call "Subscription.receiveInternal" decode this response.

2. and, "ReceiveWithTimeout" is return net.ErrClosed, can not loop call receive

**Comment by stevenh** [comment]
I'm sorry I don't understand what you're trying to say, do you have some code which demonstrates the issue you have?

**Comment by RelicOfTesla** [comment]
1.
```go

func run(ctx context.Context){
  psc := &redis.PubSubConn{Conn: conn}
  err := psc.Subscribe(topicStr)
  for {
    r: = psc.ReceiveContext(ctx)   // add this
    err, ok := r.(error)
    _ = ok
    if errors.Is(v, context.DeadlineExceeded) || errors.Is(v, context.Canceled) {
        break; // break loop
    }
    msg, ok := r.(redis.Message)
    // ....

    // if not have the psc.ReceiveContext(ctx), and i try "v, err := redis.ReceiveContext(psc.Conn, ctx)"
    // the v was can not convert redis.Message, because not decode by Subscription.receiveInternal
    // so , please add PubSubConn.ReceiveContext
  }
}
func main(){
   ctx,cancel := context.WithCancel(context.TODO())
   go run(ctx)
   time.Sleep(time.Second*10)
    cancel()
   time.Sleep(time.Second*10)
}
```


2.
```go
for {
   v := psc.ReceiveWithTimeout(time.Second)
  fmt.Println(v) 
  // first print: os.ErrDeadlineExceeded,  and this connection was closed!!!!
  // second print: net.ErrClosed  
}


```

**Comment by stevenh** [comment]
To confirm my understanding you're looking for a new feature `PubSubConn.ReceiveContext(ctx context.Context)`?

You're also saying that `psc.ReceiveWithTimeout` returns an different error indicated the connection is closed after a timeout occurs. This is indeed the case, and is by design, and that would also be the same for a `Context` method as a timeout is treated as a fatal error, which can be seen [here](https://github.com/gomodule/redigo/blob/574218b5788d47ef16ad8eb15a6704314a3e42d5/redis/conn.go#L737). It's a fatal error as with you can't be sure what state the connection is in, so it must be closed.

**Comment by RelicOfTesla** [comment]
These are two questions.....   second question it was an unexpected discovery

**Comment by stevenh** [comment]
So to confirm you should be able to use `psc.ReceiveContext(...)` to achieve what you want, with the exception that on timeout you're psc will be broken and hence will need to be set back up.

If you're seeing an unexpected result, please provide a working example and the error you are seeing.
